from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout, QHBoxLayout
from PyQt5.QtCore import Qt
app = QApplication([])
main_win = QWidget()
main_win.resize(300, 200)
main_win.setWindowTitle('Believe it or not')
statement = QLabel('Mammals with the largest ears are elephants!')
btn_yes = QPushButton('Yes')
btn_no = QPushButton('No')
line1 = QHBoxLayout()
line2 = QHBoxLayout()
line1.addWidget(statement, alignment = Qt.AlignCenter)
line2.addWidget(btn_yes)
line2.addWidget(btn_no)
line3 = QVBoxLayout()
line3.addLayout(line1)
line3.addLayout(line2)
main_win.setLayout(line3)
main_win.show()
app.exec_()
